config/routes.rb
Rails.application.routes.draw do
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  post 'signup', to: 'users#create'
  post 'logout', to: 'posts#index'

  resources :users, only: :show
  resources :sessions
  resources :posts do
      resources :comments
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to => 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :text, :user_id, :post_id, presence: true

  delegate :name, to: :user, prefix: true
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments, dependent: :destroy

  #attr_accessor :user_id, :description
  validates :description, :user_id, presence: true

  delegate :photo, :name, to: :user, prefix: true

  def user_name
    user.name
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy

  VALID_INPUTS = /[[:ascii:]]+/

  #attr_accessor :email, :password, :password_confirmation
  validates :name, presence: true, length: { maximum: 50 },
        format: { with: VALID_INPUTS }
  validates_uniqueness_of :email, presence: true, format: { with: VALID_INPUTS }
  validates :password, presence: true, length: { minimum: 8 },
        format: { with: VALID_INPUTS }
    validates :password_confirmation, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private

  def logged_in?
    @logged_in ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :logged_in?
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_with_http_digest, only: :create
  before_action :is_owner?, only: :destroy

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params.merge(user_id: logged_in?.id))
    if @comment.valid?
      redirect_to root_path
    else
      flash[:alert] = "Invalid attributes."
      redirect_to root_path
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to root_path
  end

  private

  def comment_params
    params.require(:comment).permit(:text, :post_id)
  end

  def is_owner?
    @comment = Comment.find(params[:id])
    if @comment.user != current_user
      redirect_to root_path
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_with_http_digest, only: [:new, :create]
  before_action :is_owner?, only: [:edit, :update, :destroy]

  def index
    @posts = Post.all.order('created_at DESC').includes(:user, comments: :user)
  end

  def new
    @post = Post.new
  end

  def create
    @post = logged_in?.posts.create(post_params)
    if @post.valid?
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.update(post_params)
    if @post.valid?
      redirect_to root_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to root_path
  end

  def show
    @post = Post.find(params[:id])
  end

  private

  def is_owner?
    redirect_to root_path if Post.find(params[:id]).user != logged_in?
  end

  def post_params
    params.require(:post).permit(:user_id, :description)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: 'Logged in!'
    else
      flash.now.alert = 'Email or password is invalid'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: 'Logged out!'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(allowed_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, notice: 'Thank you for signing up!'
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def allowed_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/index.html.erb
<% @posts.each do |post| %>
  <%= post.user.name %>
  <%= post.description %>
  <% if post.user == logged_in? %>
    <%= link_to 'Edit Post', edit_post_path(post.id) %>
  <% end %>

  <% post.comments.each do |comment| %>
    <p><%= comment.user.name %> <%= comment.text %></p>
    <% if comment.user == logged_in? %>
      <%= link_to 'Delete', post_comment_path(post_id: post.id, id: comment.id), method: :delete %>
    <% end %>
  <% end %>

  <% if logged_in? %>
    <%= simple_form_for Comment.new, url: post_comments_path(post), method: :post do |f| %>
      <%= f.input :text, label: 'Comment', placeholder: 'Add a comment...'  %>
      <%= f.submit 'Post', class: 'btn btn-primary btn-block' %>
    <% end %>
  <% end %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Postapp</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" type="text/css" href="/app/assets/stylesheet/master.css">
    <link href="https://fonts.googleapis.com/css?family=Audiowide|Ruda|Sedgwick+Ave+Display" rel="stylesheet">
  </head>

  <body>
  <div id = "wrap">
    <%= render 'shared/nav' %><!--Navbar-->
    <br>

    <div class = "container">
      <div class = "row">
        <div class = "col-xs-12 col-md-10 col-md-offset-1">
          <%= render 'shared/flash_messages' %>
          <%= yield %>
        </div>
      </div>
    </div>

  </div><!-- Wrap -->

  <%= render 'shared/foot' %><!--Footer-->

  </body>
</html>

app/views/posts/edit.html.erb
<h3>Edit Post</h3>

<%= simple_form_for @post do |f| %>
  <%= f.input :description %>
  <%= f.submit 'Update', class: 'btn btn-default btn-block' %>
<% end %>

app/views/posts/index.html.erb
<section class="posts">
  <% @posts.each do |post| %>
  <div class="post_box">

    <div class="post_header">
      <%= post.user_name %>
      <br>
      <span class="timestamp pull-left"><%= distance_of_time_in_words(DateTime.now, post.created_at) %> ago</span>
    </div>

    <div class="post_body">
      <%= post.description %>
    </div>
    <hr>

    <div class="content">
      <ul class="list-inline btn-group btn-group-sm">
        <li><%= link_to 'View Post', post_path(post.id), class: 'btn btn-default btn-block' %></li>
        <% if post.user == logged_in? %>
          <li><%= link_to 'Edit Post', edit_post_path(post.id), class: 'btn btn-default btn-block' %></li>
          <li><%= link_to 'Delete Post', post_path(post.id), method: :delete, class: 'btn btn-default btn-block' %></li>
        <% end %>
      </ul>
    </div>

    <div class="post_comments">
        <% post.comments.each do |comment| %>
          <%= link_to comment.user_name,  user_path(comment.user_id) %> <%= comment.text %><br>
        <% end %>
    </div>
    <hr>
    <% if logged_in? %>
      <%= simple_form_for Comment.new, url: post_comments_path(post), method: :post do |f| %>
        <%= f.input :text, label: 'Comment', placeholder: 'Add a comment...' %>
        <%= f.submit 'Post', class: 'btn btn-primary btn-block' %>
      <% end %>
    <% end %>
  </div>
  <% end %>
</section>

app/views/posts/new.html.erb
<h3>New Post</h3>

<%= simple_form_for @post do |f| %>
  <%= f.input :description %>
  <%= f.submit 'Post', class: 'btn btn-default btn-block' %>
<% end %>

app/views/posts/show.html.erb
<div class="post_box">
  <div class="post_header">
    <%= @post.user.name %>
    <br>
    <span class="timestamp pull-left"><%= distance_of_time_in_words(DateTime.now, @post.created_at) %> ago</span>
  </div>

  <div class="post_body">
    <%= @post.description %>
  </div>

  <div class="content">
    <ul class="list-inline btn-group btn-group-sm">
      <% if @post.user == logged_in? %>
        <li><%= link_to 'Edit Post', edit_post_path(@post.id), class: 'btn btn-default btn-block' %></li>
        <li><%= link_to 'Delete Post', post_path(@post.id), method: :delete, class: 'btn btn-default btn-block' %></li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <% if message_type == "notice" %>
    <p class="alert alert-info alert-dismissible text-center"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button><%= notice %></p>
  <% elsif message_type == "alert" %>
    <p class="alert alert-danger alert-dismissible text-center"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button><%= alert %></p>
  <% else %>
    <div class="alert alert-<%= message_type %> alert-dismissible text-center"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button><%= message %></div>
  <% end %>
<% end %>

app/views/shared/_foot.html.erb
<div class="footer text-center">
  <p>© KarnaDeepak <%= Date.today.year %> All Rights Reserved</p>
</div>

app/views/shared/_nav.html.erb
<div class="navbar-default">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="/"><i class="fa fa-pencil" aria-hidden="true">PostApp</i></a>
  </div>

  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li><%= link_to 'New Post', new_post_path %></li>
          <li><%= link_to 'Logout', logout_path %></li>
        <% else %>
          <li><%= link_to "Sign Up", signup_path %></li>
          <li><%= link_to "Log In", login_path %></li>
        <% end %>
    </ul>
  </div>
</div>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= form_for @user, url: signup_path do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit "Sign Up", class: 'btn btn-default btn-block' %></div>
<% end %>

app/views/users/show.html.erb
<div class="prof_header">

  <div class="row">
    <div class="col-xs-4">
      <%= @user.name %>
    </div>
    <%= @user.description %>

    <span class="count"><%= @user.posts.count %></span> posts

<div class="prof_post_box">
  <div class="row">

    <% @user.posts.each do |post| %>
      <div class="col-xs-6">
        <%= post.description %>
      </div>
    <% end %>
  </div>
</div>